//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_RealeState.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.Flats = new HashSet<Flat>();
            this.PropertyImages = new HashSet<PropertyImage>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Total_Flat { get; set; }
        public string Total_Floor { get; set; }
        public Nullable<bool> Lift { get; set; }
        public Nullable<bool> Generator { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Caretecar { get; set; }
        public int CityId { get; set; }
        public Nullable<bool> Parking { get; set; }
        public string Description { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flat> Flats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyImage> PropertyImages { get; set; }
    }
}
