//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_RealeState.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent_Payment
    {
        public int Id { get; set; }
        public int RentId { get; set; }
        public int Payment_Code { get; set; }
        public Nullable<System.DateTime> DataTime { get; set; }
        public double Amount { get; set; }
    
        public virtual Rent Rent { get; set; }
    }
}
