//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_RealeState.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rent()
        {
            this.Rent_Payment = new HashSet<Rent_Payment>();
        }
    
        public int Id { get; set; }
        public int FlatId { get; set; }
        public int UserId { get; set; }
        public double Price { get; set; }
        public Nullable<bool> Paper { get; set; }
        public Nullable<int> Contact { get; set; }
    
        public virtual Flat Flat { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent_Payment> Rent_Payment { get; set; }
    }
}
